export { HomeView } from "./home"
export { DisplayView } from "./display"
export { CandyMachineView } from "./candymachine"
export { ExploreView } from "./explore"
export { CheckWalletView } from "./checkwallet"
